[package]
name = "pio"
version = "0.1.0"
authors = ["snek"]
edition = "2018"

[dependencies]
paste = "1.0"
lalrpop-util = { git = "https://github.com/devsnek/lalrpop.git", branch = "better" }
hashbrown = "0.9"

[build-dependencies]
lalrpop = { git = "https://github.com/devsnek/lalrpop.git", branch = "better" }
