[package]
name = "pio"
version = "0.1.0"
authors = ["snek"]
edition = "2018"

[dependencies]
paste = "1.0"
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git", rev = "a8afe7d" }
hashbrown = "0.9"

[build-dependencies]
lalrpop = { git = "https://github.com/lalrpop/lalrpop.git", rev = "a8afe7d" }

[dev-dependencies]
test-generator = "0.3.0"
pretty_assertions = "0.6"
