[package]
name = "pio-parser"
version = "0.1.0"
authors = ["snek"]
edition = "2018"
resolver= "2"

[dependencies]
lalrpop-util = { version = "0.19.6", features = ["lexer"] }
pio = { path = ".." }

[build-dependencies]
lalrpop = "0.19.6"
