[package]
name = "pio-proc"
version = "0.1.0"
authors = ["snek"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
codespan-reporting = "0.11"
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git", rev = "a8afe7d" }
pio = { path = ".." }
